# Polievky

## Zeleninová kojenecká polievka

Porcia: 4 osoby

Ingrediencie:

* 5-6 mrkiev
* 1/2 zeler
* 1 kaleráb
* 2 petržleny alebo 2 paštrnáky
* 1/2 kávovej lyžičky soli
* Trochu oleja
* Petržlenová vňať

Postup:

1. Nastrúhame všetku zeleninu na väčšie rezance.
2. Vo väčšom hrnci rozohrejeme olej, resp. masť.
3. Restujeme zeleninu 3 minúty.
4. Zalejeme vodou 2l, osolíme.
5. Varíme cca 15 minút.
6. Dozdobíme vnaťou.

## Zemiaková na kyslo

Porcia: 4 osoby

Ingrediencie:

* 6 zemiakov
* kyslá smotana/šlahačková smotana
* 1/2 kávovej lyžičky soli
* 1 kávova lyžička múky v prípade, že nepoužívame šlahačkovú smotanu
* kôpor
* čierne korenie
* nové korenie
* bobkový list
* ocot

Postup:

1. Ošúpeme zemiaky a nakrájame ich na kocky.
2. Dáme do hrnca 2l vody, zemiaky, korenie, soľ, bobkový list.
3. Zemiaky uvaríme do mäkka, cca 15 minút.
4. Dáme hrniec preč z ohna, rozmiešame kyslú smotanu s múkou.
5. Vlejeme do hrnca pripravenú zmes a dame späť na plameň.
6. Uvedieme do varu a odstavíme.
7. Pridáme kôpor a ocot.



## Števkova vianočná kapustnica

Ingrediencie:

POMER MÄSO KU KAPUSTE:   1:1,25
* údené mäso - stehno (tvrdšie)
            - pripadne krkovičku

* klobása - koľko sa ti zmestí do hrnca podľa chuti
* kapusta    - 1/2 sladšia kyslá (aj so šťavou)
            - 1/2 kyslejšia kyslá (aj so šťavou)
* cibuľa (1 cibuľa na 3l)
* červená paprika 1/2 polievkovej lyžice
* čierne korenie (20ks na 3l)
* zelené korenie (guličky - 3ks, na 3l)
* cukor (3 polievkové lyžice na 3l)
* masť
* slivky
* huby

Postup: (kapustnicu varíme spolu 2h)

1. Narezať mäso na kvádriky (1x1x2cm) + klobásu na valčeky s veľkosťou 2.5 cm
2. Narezať cibuľu (1 cibuľa na 3l.)
3. Masť na spodok hrnca - rozohriať
4. Po rozhorúčení pridáme do hrnca cibuľu na kocky, keď je cibuľka spenená zasypeme červenou papriku a nenecháme ju tam dlho aby nezhorkla,
 a pridáme kyslejšiu kapustu do 1/4 hrnca a podliať šťavou. 
5. Variť a dolievať vodu (viac vody ako kapusty) - pridávať postupne celú kapustu...
6. Keď začne vrieť, pridať čierne korenie a zelené korenie 
7. Keď vrie 5-10min, kapusta začína byť udusená, pridávam mastnú krkovičku ak chceme (väčší kus 5cm) xxxx
8. Otáčať a premiešavať + pridáme údené mäso ("šunka")
9. Pridávame klobásu (1ks=2cm).
10. Neskôr doliať a prevariť vodu.
11. Po hodine a pol varenia, z cukru vytvoríme karamel a pridáme do kapustnice. 
12. Posledných 15 min - pridáme slivky a huby. 


