# Mäsové jedlá

## Perkelt

Porcia: 4 osoby

Ingrediencie:

* 650g kuracieho, resp. morčacieho mäsa
* 2ks stredne veľké cibule
* 1ks smotana resp. šľahačka
* 1/2 kávovej lyžičky soli
* bobkový list
* 1 káv. lyž. - červená paprika sladká

Postup:

1. Mäso nakrájame na kocky. Cibuľku nakrájame nadrobno. 
2. Osmahneme cibuľku do sklovita, 1-2min.
3. Do cibuľky pridáme červenú papriku. Krátko pomiešame a pridáme mäso.
4. Do obelenia mäsa ho miešame (2min).
5. Podlejeme mäso vodou, aby bolo mierne zaliate a osolíme. 
6. Pridáme bobkový list. 
7. Varíme domäkka(kuracie 15 min., morčacie 20 min., s kosťou aj 30min.).
8. Dáme dole z plameňa a pridáme smotanu(kyslú s troškou múky, sladkú môžeme aj bez múky).
9. Dáme späť na plameň a povaríme do zovretia.   


## Karé na šlahačke 
 
Porcia: 5 osôb 

Ingrediencie:

* 1 kg vykostené karé
* hl.múka zmiešaná s červenou paprikou
* 1 smotana na šlahanie
* soľ

Postup:

1. Mäso nakrájame na plátky cca 1 cm hrubé, vyklepeme a nasolíme.
2. Obalime v múke zmiešanej s červenou paprikou a na panvici prudko opečieme.
3. Kladieme na plech kde na záver vylejeme olej z panvice a polejeme šlahačkou.
4. Pečieme cca 1 hodinu až šlahačka zhrudkovatie.
5. Podávame so zemiakmi a paprikovo - rajčinovým šalatom alebo uhorkovým resp.kyslou uhorkou. 

## Lasagne Bolognese

Ingrediencie:

0.66kg bravčové mleté
1.33kg hovädzie mleté
Paradajkový pretlak - najlepšie aj s rajčinovou dužinou
Cibuľa
Zeler - ak máme tak rapíkatý
Mrkva
150g Maslo
150g Hladká múka
1l Mlieka
Červené víno
Olej

Postup:

1. Sprudka opečieme mäso na oleji
1. Po karamelizácii mäsa pridáme na kocky nakrájanú mrkvu, zeler a cibuľu. Vytvoríme zeleninový základ - soffrito.
1. Pridáme pohar vína aby sa mäso prestalo pripaľovať.
1. Pridáme rajčiny a vodu.
1. Pridáme tymián, bobkový list ktoré neskôr vyberieme.
1. Varíme 2 hodiny.
1. Béchamel spravíme z jedného dielu masla a múky. Po zohriatí pridáme liter mlieka a muškátový oriešok.
1. Pri skladaní začneme béchamelom, vrstva cesta, béchamel, mäso, parmezán a opäť cesto a tak ďalej. Končíme vrstvou béchamelu.
