# Vegetariánske jedlá

## Tekvicový prívarok

Ingrediencie:

* 1ks tekvice(približne 1kg)
* 1 stredná cibuľa
* trochu oleja
* 1 kyslá smotana
* nasekaný kôpor
* soľ, cukor
* 1 pl hladkej múky

Postup:

1. Cibuľu nakrájame na kocky, orestujeme do zlatista na oleji(2-3min).
1. Pridáme ošúpanú, vydlabanú(jadierka) a nastrúhanú tekvicu(na rezance), pomiešame a dusíme 10-15 minút.
1. Dáme preč z plameňa a vmiešame smotanu s múkou, osolíme a pridáme malé množstvo cukru.
1. Vrátime späť na oheň a privedieme do varu. Nevaríme.
1. Ozdobíme kôprom. Podávame so strateným vajcom, špekáčkom, alebo niečím podobným.

## Patizónové placky

Ingrediencie:

* 1 patizón
* 1 vajce
* petržlenová vňať
* 1 pl hladkej múky/strúhanky
* olej/masť na smaženie
* soľ, solčanka

Postup:

1. Patizón rozštvrtíme, ošúpeme a vydlabeme.
2. Nastrúhame ho na rezance.
3. Pridáme žĺtok, nasekanú vňať, soľ, solčanku a múku a rozmiešame.
4. Z bielku vyšlaháme sneh a zľahka pridáme do zmesy.
5. Do rozhorúčeného oleja lyžicou kopček zmesy, ktorý vytvarujeme na placku priamo v panvici.
6. Smažíme z oboch strán.

## Parené buchty

Ingrediencie:

* 500 g polohrubá múka
* 400 ml vlažného mlieka
* 42 g kvasníc
* 1 pol. lyžica kryštal.cukor
* maslo na poliatie buchiet
* posypať môžeme tvarohom, makom, orechami pridane grankom a posypať práš. cukrom
* trocha soli (na špicu noža
* slivkový lekvár
 
Postup:

1. Do cca 200 ml. vlažného mlieka rozdrobíme kvasnice a pridáme kryštálový cukor
2. Preosejeme si múku, pridame štipku soli, pridame vykysnutý kvások  a zvyšné mlieko. Všetko vypracujeme a necháme vykysnúť na teplom mieste cca 30-45 minút.
3. Cesto si vylejeme na pomúčenú dosku mierne vyválame asi na hrubku 1 cm. Odkrajujeme štvorce, ktoré plníme slivkovým lekvárom. Spojíme do batôžka a na pomúčenej doske necháme podkysnúť.
4. Varíme nad parou cca 10 minút a to na gáze alebo na paraku na knedlu. parák si trosku naolejujem nech sa neprilepí buchta.
5. Posypeme podľa chuti.

## Bryndzové pirohy

Ingrediencie:

* 500 g zemiakov uvarených deň vopred v šupke
* 200 g polohrubej muky resp. hrubej
* 1 vajce
* 300 g bryndze
* 100 g údená slaninka 
* prípadne cibuľa osmažená na polo kolieska
 
Postup:

1. Uvarené zemiaky pretlačíme resp. postrúhame na jemno
2. Pridáme vajíčko a múku podľa potreby a vypracujeme vláčne cesto.
3. Cesto rozvaľkáme a vykrajujeme pohárom alebo formičkou kolieska na ktoré dáme plnku - bryndzu zmiešanú s vareným postruhaným zemiakom.
4. Kolieska preložíme na polovicu a uzavrieme vidličkou. Varíme v osolenej vriacej vode až vyjdú na povrch.
5. Podávame ich s kyslou smotanou posypanou vyškvarenou slaninkou alebo cibuľkou. Ľubica ich má rada aj s kôpríkom.


## Dukatove buchticky  

*Ingrediencie :

250 g hladkej m
