# Dezerty

## Bábovka

Ingrediencie: 

* 4 vajcia
* 20 dkg hl. múky
* 20 dkg cukru
* prášok do pečiva celý 
* kakao 2 lyžice
* 1 dcl oleja
* 1 dcl vody

Postup:

1. Vyšlaháme sneh zo štyroch vajec.
1. 3 žĺtka vyšlaháme s cukrom, pridáme muku zmiešanú s práškom do pečiva, pridáme olej, vodu a zamiešame.
1. Nakoniec pridáme zľahka sneh.
1. 1/3 cesta zmiešame s kakaom.
1. Maslom, prípadne olejom vymastíme bábovkovú formu a omúčime ju polohrubou alebo hrubou múkou(nie hladkou múkou, lebo tá je v ceste).
1. Do formy nalejeme väčšinu bieleho cesta. Nato nalejeme tmavé a ešte zbytok bieleho cesta navrch.
1. Pečieme pri 180 stupňoch celzia cca 30 minút. Po cca 20 minútach skontrolujeme ihlicou, či je bábovka prepečená. Ak sa nalepí na ihlicu cesto, nie je dopečená.

## Perník na plech 

Ingrediencie:

* 2 celé vajcia
* 40 dkg hl. múky
* 2 dcl oleja
* 3 dcl mlieka
* 30 dkg cukru
* 1 lyžica medu
* 3 lyžice džemu
* 1 kypriaci prášok do perníka
* 1/2 káv. lyžičky soda bicarbona
* 2 až 3 lyžičky kakaa

Postup:

1. Všetko zmiešame a vylejeme na vymastený a múkou vysypaný plech. Pečieme cca 30 minút pri 180 stupňov celzia.

## Bublanina

Ingrediencie:

* 5 vajec
* 240g práškového cukru
* 300g polohrubej múky
* 1/2 balíčka prášku do pečiva (t.j. 6-8g prášku do pečiva)
* 0.1l repkového/slnečnicového oleja
* 0.1l vody
* ovocie
* štipka soli

Postup:

1. Z bielkov z vajec vyšlaháme sneh so štipkou soli. Miska musí byť odmastená.
1. Začneme jednou minútou pomalého mixovania bielkov.
1. Pridáme na rýchlosti až kým sneh nie je tuhý.
1. V samostatnej miske vyšlaháme všetky žĺtka s cukrom do zbelenia.
1. Múku preosejeme s práškom do pečiva v samostatnej miske.
1. Postupne do žĺtkov na striedačku prisypávame múku a prilievame olej a vodu.
1. Vymiešame do homogénnej hmoty.
1. Vypneme robota a ručne vmiešame sneh opäť na homogénnu hmotu.
1. Miešame zľahka, aby sneh nesplasol.
1. Cesto vylejeme na olejom vymastený a múkou vysypaný plech. Poukladáme ovocie a pečieme vo vopred vyhriatej rúre na 180 stupňov celzia pri hornom a dolnom ohreve. V prípade použitia teplovzdušného programu pečieme pri 160 stupňoch.
1. Pečieme od 30-35 minút v závislosti od druhu ovocia. Bobulovité ovocie pečieme pri spodnej hranici tohto intervalu.

## Nepečená jablková torta

Ingrediencie:

* 1 balíček piškótov
* 1kg očistených jabĺk zbavených šupy, jadierok a nakrájaných na kocky
* 2 Zlaté klasy
* cukor podľa chuti
* čokoládu na varenie resp. horkú

Postup:

1. Formu tortovú, alebo akúkoľvek si vystelieme piškótami, nalejeme uvarené jablká s dvomi Zlatými klasmi, naskladáme dalšie piškóty a necháme vychladnúť. Nakoniec môžeme poliať čokoládou. 

## Bratislavské rožky

Ingrediencie:

Cesto:

* 500g hladkej múky
* 500g polohrubej múky
* 60g droždia
* 4g soli
* 130g cukru
* 300g masla
* 0,2l mlieka

Plnka:

* 500g maku/orechov
* 200g práškového cukru
* 1 vanilkový cukor
* 0,25l mlieka
* 2 žĺtky na potretie

Postup:

1. Cukor rozpustíme v mlieku a za stáleho miešania zohrievame.
1. Pridáme pomletý mak alebo orechy a zohrievame za stáleho miešania, až kým zmes nestuhne.
1. Vykysnuté cesto rozdelíme na približne 30-gramové kúsky, z ktorých vyformujeme malé bochníčky a rozvaľkáme na ováliky.
1. Do ich stredu vložíme plnku sformovanú do valčeka, hmotnosť plnky musí byť aspoň taká ako hmotnosť cesta.
1. Oválik s plnkou zatočíme a vytvarujeme z nich rožky. Kladieme ich na plech spojom nadol, aby sa rožok pri pečení neotváral.
1. Každý potrieme rozšľahaným vajíčkom a ešte pred pečením odložíme na teplejšie miesto, aby mierne nakysli a glazúra sa popraskala, mramorovala. Pre výraznejší efekt tento postup môžeme opakovať.
1. Pečieme pri teplote okolo 200 stupňov celzia približne 12 minút.
1. Náplň môže byť len maková alebo orechová a musí tvoriť minimálne 40 percent z hmotnosti rožka.
1. Makový musí mať tvar podkovičky, rožok s orechovou náplňou tvar písmena C.
1. Povrch rožkov musí byť lesklý a mramorovaný.

## Hanácke koláče

Ingrediencie:

* 750 g polohrubej múky - preosiať 
* 400 ml vlažného mlieka
* 2 čl cukor
* 40 g droždie
* 180 g rozpustené maslo
* 100 g práškoveho cukru
* 3 ks žĺtka
* 1 ks vanilkový cukor
* 1 ćl soli
* citr. kôra

Tvarohová plnka:

* 1 kg tvarohu
* 150 g práškového cukru
* 2 bal. vanilkového cukru
* 75 g masla

Mrvenička:

* 40 g hrubá múka
* 40 g maslo z chladničky
* 40 g práškového cukru

Postup:

1. Z droždia s trochou mlieka a cukru necháme vykysnúť kvások
2. Do múky pridáme kvások, cukor, žĺtky, soľ, tuk, vlažné mlieko a vymiesime cesto, ktoré sa musí od misy odliepať. Necháme ho vykysnúť na teplom mieste cca 1 hod.
3. Na doske vygúľame cesto na hrúbku cca 1/2 cm odkrajujeme si z cesta štvorce, ktoré naplníme tvarohovou plnkou. Dobre uzavrieme a vytvoríme necháme na vymastenom plechu podkysnúť.
4. Do buchtičiek malým pohárikom vylačíme jamky.
5. Okraj buchtičiek potrieme rozšlahaným vajíčkom. Do jamiek vložíme tuhší džem najlepšie slivkový.
6. Posypeme mrveničkou
7. Dáme piecť pri teplote 180 stupňov celzia 


## Bezlepkový koláč 

Torta o priemere 24 cm.

Ingrediencie :

* 120 g masla
* 190 g trstinového cukru
* 1 vanilkový lusk
* kôra z bio citóna
* 4 šťastné vajce
* 240 g mletých mandlí rep. orechov
* 300 g ricotty alebo tvarohu
* štipka soli

Postup:

1. Rúru predhrejeme na 170 stupňov
2. Dno a boky tortovej formy vystelieme peč.papierom
3. Zmeknuté maslo vyšlaháme so 150 g cukru so semienkami z lusku citr. kôrou až do zbelenia
4. Postupne zašlahajte jeden po druhom žĺtka na záver miešajte mandlovú múku a ricottu alebo tvaroh
5. V čistej miske so štipkou soli vyšlaháme tuhý sneh so 4 bielkov
6. Zašlaháme 40 g cukru a potom vmiešame postupne k mandlovej zmesi
7. Pečieme 45 - 50 min.
8. Necháme vychladnúť v tortovej forme 


## Vanilkové rohlíky

Asi 70 ks rohlíčkov.

Ingrediencie :

* Práškový cukor 8.33 dkg
* Orechy 16.66 dkg
* Maslo 25 dkg
* Hladká múka 33.32 dkg
* Štipka soli

Postup:

1.Cesto dobre vypracujeme a hneď s ním pracujeme.
2.Ušúlame si valec ukrajujeme kúsky vaľkame a vyformujeme rohliček.
3.Pečieme do bleda, necháme na plechu vychladnúť a opatrne vyváľame vo vanilkovom cukre.


## Lepené kolieska čo ľúbi Peťka


Ingrediencie :

* 21 dkg hl. múky
* 7 dkg prášk. cukor
* 14 dkg masla
* 2 dkg kakaa
* 1 bal. vanilk. cukru

Postup:

1.Zmiešame ingrediencie vyvaľkáme a vykrajujume menšie kolieska.
2.Vymiešame maslo s cukrom a lepia sa 2 kolieska spolu.
3.Nakoniec sa polejú čokoládou a ozdobia lúpanou mandlou.

## Linecké "Hanča"


Ingrediencie :

* 600g hl. múky
* 400g masla
* 200g prášk. cukru
* 4 žĺtka
* kakao, káva, mleté orechy, mleté mandle

Postup:

1.Zmiešame ingrediencie vyvaľkáme a vykrajujeme. 
2.Zlepujeme s kyslejším lekvárom.

## Opekance s makom


Ingrediencie :

* 500g hrubej múky
* 2,5 dl mlieka
* 1 vajce
* 80g margarinu
* kryšt. cukor
* droždie - kvások
* mak, med, maslo - navrch

Postup:

1. Do múky pridáme vajce, cukor, margarin, mlieko, z droždia kvások - vypracujeme cesto, necháme nakysnúť.
2. Potom robíme šúľky - 1,5 cm - dáme na vymastený plech. 
3. Necháme nakysnúť, upečieme do ružova (nevajcujeme).
4. Hotové pokrájame, prelejeme horúcou vodou, posypeme mletým makom, cukrom a roztopeným maslom. Nakoniec polejeme medom.

## Kolieska Majky Matovičovej


Ingrediencie :

* 21dkg hl. múky
* 18dkg margarin
* 7dkg prášk. cukru
* 5dkg pomleté orechy
  2dkg kakaa 
* 1 káv. lyž. škorice

Postup:

1.Všetko zmiesime, vyvaľkáme a vykrajujeme kolieska
2.Uvaríme si plnku. Hrsť hrubej múky,1 dcl mlieka,hrsť kryštalového cukru  a uvaríme hustú kašu. 
3.35 - 40g masla vymiešame s 40 g práškového cukru a potom postupne vmiešavame vychladnutú hustú kašu
4.Zlepujeme s krémom vždy 2 kolieska spolu.
5.Vrch polejeme s čokoládou a navrch dáme orech alebo ošupanú mandličku.
